name: ðŸš€ Deploy Frontend on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: âœ¨ Create .env.production (hardcoded values)
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=https://trendmorph-backend.vercel.app" 
       

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ”¨ Build Next.js
        run: npm run build

      - name: ðŸ“‚ Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: 192.250.235.20
          username: stocknepal@stocknepal.nepoproduct.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: out/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/tests*
            **/*.log
            